apiVersion: v1
kind: Namespace
metadata:
  name: dns-resolver
  labels:
    name: dns-resolver

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
  namespace: dns-resolver
  labels:
    app: dns-resolver-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dns-resolver-web
  template:
    metadata:
      labels:
        app: dns-resolver-web
    spec:
      containers:
        - name: web
          image: registry-intl.cn-hangzhou.aliyuncs.com/fachrin/dns-resolver:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          env:
            - name: build_date
              value: '{{build_date}}'

---

apiVersion: v1
kind: Service
metadata:
  name: web
  namespace: dns-resolver
spec:
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: dns-resolver-web

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: web
  namespace: dns-resolver
  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/cluster-issuer: "letsencrypt-universal"
spec:
  tls:
    - hosts:
        - resolver.fachr.in
      secretName: dns-resolver-webpage-tls
  rules:
    - host: resolver.fachr.in
      http:
        paths:
          - pathType: Prefix
            path: "/"
            backend:
              service:
                name: web
                port:
                  number: 80
