// Code generated by mockery v2.14.0. DO NOT EDIT.

package resolver

import (
	context "context"

	dns "github.com/parinpan/dns-resolver/pkg/dns"
	mock "github.com/stretchr/testify/mock"
)

// dnsResolverClientMock is an autogenerated mock type for the dnsResolverClient type
type dnsResolverClientMock struct {
	mock.Mock
}

// ExchangeContext provides a mock function with given fields: ctx, question
func (_m *dnsResolverClientMock) ExchangeContext(ctx context.Context, question dns.Question) ([]dns.Data, error) {
	ret := _m.Called(ctx, question)

	var r0 []dns.Data
	if rf, ok := ret.Get(0).(func(context.Context, dns.Question) []dns.Data); ok {
		r0 = rf(ctx, question)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]dns.Data)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, dns.Question) error); ok {
		r1 = rf(ctx, question)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTnewDnsResolverClientMock interface {
	mock.TestingT
	Cleanup(func())
}

// newDnsResolverClientMock creates a new instance of dnsResolverClientMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func newDnsResolverClientMock(t mockConstructorTestingTnewDnsResolverClientMock) *dnsResolverClientMock {
	mock := &dnsResolverClientMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
